image: node:16 # Docker imajini tanlash (Node.js uchun)

stages:
  - install
  - build
  - test
  - deploy

# Install stage: kerakli bog'liqliklarni o'rnatish
install:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

# Build stage: Next.js loyihasini qurish
build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - .next/
    expire_in: 1 hour

# Test stage: Testlarni ishga tushirish
test:
  stage: test
  script:
    - npm run test
  only:
    - master

# Deploy stage: Loyiha ishlab chiqarish serveriga joylashtirish (masalan, Vercel yoki boshqa server)
deploy:
  stage: deploy
  script:
    - npm run deploy
  only:
    - master
